# .github/workflows/ci-cd.yml
name: UI-Topia CI/CD Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: omerbenda98/ui_topia
  GITOPS_REPO: omerbenda98/uitopia-cd

jobs:
  # Runs on dev branch and PRs (not main)
  build-test-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        env:
          VERSION: ${{ github.run_number }}
        run: |
          docker build -t ${IMAGE_NAME}:${VERSION} .
          docker tag ${IMAGE_NAME}:${VERSION} ${IMAGE_NAME}:latest

      - name: Start application for testing
        env:
          VERSION: ${{ github.run_number }}
        run: |
          # Create a simple docker-compose for testing
          cat > docker-compose.test.yml << EOF
          version: '3.8'
          services:
            app:
              image: ${IMAGE_NAME}:${VERSION}
              ports:
                - "3000:3000"
              environment:
                - NODE_ENV=test
          EOF

          # Start the application
          docker compose -f docker-compose.test.yml up -d

          # Wait for app to be ready
          echo "Waiting for application to start..."
          for i in {1..30}; do
            if curl -f http://localhost:3000 > /dev/null 2>&1; then
              echo "Application is ready!"
              break
            fi
            echo "Waiting... ($i/30)"
            sleep 10
          done

      - name: Setup Python for Tests
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run Selenium Tests
        run: |
          # Create virtual environment and install dependencies
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r selenium-tests/requirements.txt

          # Run tests
          pytest ./selenium-tests/test_simple.py --verbose

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/dev' # Only push on dev branch, not PRs
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        if: github.ref == 'refs/heads/dev' # Only push on dev branch, not PRs
        env:
          VERSION: ${{ github.run_number }}
        run: |
          docker push ${IMAGE_NAME}:${VERSION}
          docker push ${IMAGE_NAME}:latest

      - name: Update Staging Version in GitOps Repo
        if: github.ref == 'refs/heads/dev' # Only update staging on dev branch
        env:
          VERSION: ${{ github.run_number }}
          GH_TOKEN: ${{ secrets.GITOPS_TOKEN }}
        run: |
          # Clone GitOps repo
          rm -rf gitops
          git clone https://${GH_TOKEN}@github.com/${GITOPS_REPO} gitops
          cd gitops

          # Install yq for YAML editing
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

          # Update staging values file
          yq eval '.app.tag = env(VERSION)' -i k8s/helm-charts/uitopia-app/values-staging.yaml
          echo "${VERSION}" > stage_version.txt

          # Commit and push
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add .

          # Only commit if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "Update staging version to ${VERSION}"
            git push origin main
          else
            echo "No changes to commit"
          fi

      - name: Create Pull Request to Main
        if: github.ref == 'refs/heads/dev' # Only create PR from dev branch
        env:
          VERSION: ${{ github.run_number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN instead
        run: |
          # Check if PR already exists from dev to main
          EXISTING_PR=$(gh pr list --head "dev" --base "main" --state open --json number --jq '.[0].number')

          if [ "$EXISTING_PR" = "null" ] || [ -z "$EXISTING_PR" ]; then
            # Create new PR from dev to main
            gh pr create \
              --title "Deploy version ${VERSION} to production" \
              --body "🚀 Ready to deploy version ${VERSION} to production after successful staging tests" \
              --head "dev" \
              --base "main" 
            echo "✅ Created new PR from dev to main"
          else
            echo "ℹ️  PR already exists: #${EXISTING_PR}"
            # Update the existing PR
            gh pr edit ${EXISTING_PR} \
              --title "Deploy version ${VERSION} to production" \
              --body "🚀 Ready to deploy version ${VERSION} to production after successful staging tests"
          fi

      - name: Cleanup
        if: always()
        run: |
          docker compose -f docker-compose.test.yml down || true
          docker system prune -f

  # Runs only on main branch (when PR is merged)
  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Latest Staging Version
        id: get_version
        env:
          GH_TOKEN: ${{ secrets.GITOPS_TOKEN }}
        run: |
          # Clone GitOps repo to get the latest staging version
          rm -rf gitops
          git clone https://${GH_TOKEN}@github.com/${GITOPS_REPO} gitops
          cd gitops

          # Get version from staging version file
          if [ -f "stage_version.txt" ]; then
            VERSION=$(cat stage_version.txt)
            echo "📦 Found staging version: ${VERSION}"
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
          else
            echo "❌ ERROR: No staging version found"
            exit 1
          fi

      - name: Update Production Version in GitOps Repo
        env:
          NEW_VERSION: ${{ steps.get_version.outputs.version }}
          GH_TOKEN: ${{ secrets.GITOPS_TOKEN }}
        run: |
          # We already have the gitops repo from previous step
          cd gitops

          # Install yq for YAML editing
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

          # Update production values file
          yq eval '.app.tag = env(NEW_VERSION)' -i k8s/helm-charts/uitopia-app/values-production.yaml

          # Commit and push
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add .

          # Only commit if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "🚀 Deploy version ${NEW_VERSION} to production"
            git push origin main
            echo "✅ Updated production to version ${NEW_VERSION}"
          else
            echo "ℹ️  Production already at version ${NEW_VERSION}"
          fi

  # Notification job
  # notify:
  #   runs-on: ubuntu-latest
  #   needs: [build-test-staging, deploy-production]
  #   if: always()

  #   steps:
  #     - name: Slack Notification - Success
  #       if: |
  #         (needs.build-test-staging.result == 'success' || needs.build-test-staging.result == 'skipped') &&
  #         (needs.deploy-production.result == 'success' || needs.deploy-production.result == 'skipped')
  #       uses: 8398a7/action-slack@v3
  #       with:
  #         status: success
  #         channel: "#devops"
  #         text: |
  #           ✅ BUILD SUCCESSFUL: ${{ github.repository }} [${{ github.run_number }}]
  #           🔗 ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  #           🌐 Check your applications:
  #           - Staging: https://staging.benda.wiki
  #           - Production: https://benda.wiki
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  #     - name: Slack Notification - Failure
  #       if: |
  #         needs.build-test-staging.result == 'failure' ||
  #         needs.deploy-production.result == 'failure'
  #       uses: 8398a7/action-slack@v3
  #       with:
  #         status: failure
  #         channel: "#devops"
  #         text: |
  #           ❌ BUILD FAILED: ${{ github.repository }} [${{ github.run_number }}]
  #           🔗 ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
